version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.7"
  commands:
    - python3 -m pip install git+https://github.com/martino-vic/loanpy.git@2.0.1
  install:
  - requirements: docs/requirements.txt
