version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  build:
    executor: python/default
    steps:
      - run:
          name: Clone repo
          command: >
            git clone https://github.com/martino-vic/ronataswestoldturkic.git
      - run:
          name: Clone reference catalogues & loanpy (takes 1min15s)
          command: |
            mkdir concepticon
            cd concepticon
            git clone https://github.com/concepticon/concepticon-data.git
            cd ..
            git clone https://github.com/glottolog/glottolog.git
            git clone https://github.com/cldf-clts/clts.git
            git clone https://github.com/martino-vic/loanpy.git
      - run:
          name: install commands and loanpy
          command: |
            pip install -e ronataswestoldturkic
            pip install -e loanpy

      - run:
          name: run lexibank script
          command: >
            cldfbench lexibank.makecldf lexibank_ronataswestoldturkic.py
            --concepticon-version=v3.0.0
            --glottolog-version=v4.7
            --clts-version=v2.2.0

      - run:
          name: Create Hungarian IPA transcriptions from cldf/forms.csv
          command: |
            cd ronataswestoldturkic
            cldfbench ronataswestoldturkic.makeHortho

      - run:
          name: re-run lexibank script with Hungarian orthography
          command: >
            cldfbench lexibank.makecldf lexibank_ronataswestoldturkic.py
            --concepticon-version=v3.0.0
            --glottolog-version=v4.7
            --clts-version=v2.2.0

      - run:
          name: Install pytest-cldf
          command: pip install pytest-cldf
      - run:
          name: Test with pytest-cldf whether the dataset is cldf-conform
          command: |
            cd ronataswestoldturkic
            pytest --cldf-metadata=cldf/cldf-metadata.json test.py

      - run:
          name: Create input for Edictor and check the output
          command: |
            cd ronataswestoldturkic
            cldfbench ronataswestoldturkic.maketoedict_rc H EAH
            diff -sq H2EAHtoedict0.tsv H2EAHtoedict.tsv


workflows:
  main:
    jobs:
      - build
