version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  build:
    executor: python/default
    steps:
      - run:
          name: Clone repo
          command: >
            git clone https://github.com/martino-vic/ronataswestoldturkic.git
      - run:
          name: Clone reference catalogues (takes 1min15s) & get jq
          command: |
            mkdir concepticon
            cd concepticon
            git clone https://github.com/concepticon/concepticon-data.git
            cd ..
            git clone https://github.com/glottolog/glottolog.git
            git clone https://github.com/cldf-clts/clts.git
            sudo apt-get install jq
      - run:
          name: install commands and loanpy
          command: |
            pip install -e ronataswestoldturkic
            pip install loanpy

      - run:
          name: run lexibank script
          command: >
            cd ronataswestoldturkic &&
            cldfbench lexibank.makecldf lexibank_ronataswestoldturkic.py
            --concepticon-version=v3.0.0
            --glottolog-version=v4.7
            --clts-version=v2.2.0
            --concepticon=../concepticon/concepticon-data
            --glottolog=../glottolog
            --clts=../clts

      - run:
          name: Install pytest-cldf
          command: pip install pytest-cldf
      - run:
          name: install pytest-cldf and test if dataset is cldf-conform
          command: |
            cd ronataswestoldturkic
            pytest --cldf-metadata=cldf/cldf-metadata.json test.py

      - run:
          name: Create inputs for Edictor
          command: |
            cd ronataswestoldturkic
            cldfbench ronataswestoldturkic.maketoedict_rc H EAH
            cldfbench ronataswestoldturkic.maketoedict_ad WOT EAH
            cldfbench ronataswestoldturkic.cvgapedicted WOT EAH

      - run:
          name: Evaluate outputs from Edictor
          command: |
            cd ronataswestoldturkic
            cldfbench ronataswestoldturkic.evaledicted H EAH
            cldfbench ronataswestoldturkic.evaledicted WOT EAH

      - run:
          name: Create phonotactic inventory, check if output is good
          command: >
            cd ronataswestoldturkic && cldfbench
            ronataswestoldturkic.mineEAHinvs invsEAH.json

            cd loanpy && out=$(jq --argfile a invsEAH.json --argfile b
            .circleci_backup/invsEAH.json -n '($a | (.. | arrays) |= sort) as
            $a | ($b | (.. | arrays) |= sort) as $b | $a == $b') &&
            if [ "$out" = true ]; then   echo "OK";
            else   echo inventoriess differ; exit 1; fi

      - run:
          name: Create heuristic sound subsitution, check if output is good
          command: >
            cd ronataswestoldturkic && cldfbench
            ronataswestoldturkic.makeheur EAH heur.json

            cd loanpy && if diff heur.json .circleci_backup/heur.json;
            then echo OK; else echo heuristics differ; exit 1; fi

      - run:
          name: Mine vertical sound correspondences, check if output OK
          command: >
            cd ronataswestoldturkic && cldfbench
            ronataswestoldturkic.minesc H EAH

            cd loanpy && if diff H2EAHsc.json .circleci_backup/H2EAHsc.json;
            then echo OK; else echo heuristics differ; exit 1; fi

      - run:
          name: Mine horizontal sound correspondences, check if output OK
          command: >
            cd ronataswestoldturkic && cldfbench
            ronataswestoldturkic.minesc WOT EAH heur.json

            cd loanpy && if diff WOT2EAHsc.json
            .circleci_backup/WOT2EAHsc.json; then echo OK;
            else echo heuristics differ; exit 1; fi

      - run:
          name: Visualise sound correspondences as tsv, check if output OK
          command: >
            cd ronataswestoldturkic &&
            cldfbench ronataswestoldturkic.vizsc H EAH &&
            cldfbench ronataswestoldturkic.vizsc WOT EAH

            cd loanpy

            if diff H2EAHsc.tsv .circleci_backup/H2EAHsc.tsv
            --strip-trailing-cr -B -Z; then echo OK;
            else echo sc-tables differ for H and EAH; exit 1; fi

            if diff WOT2EAHsc.tsv .circleci_backup/WOT2EAHsc.tsv
            --strip-trailing-cr -B -Z; then echo OK;
            else echo sc-tables differ for WOT and EAH; exit 1; fi

            if diff H2EAHsc_phonotactics.tsv
            .circleci_backup/H2EAHsc_phonotactics.tsv
            --strip-trailing-cr -B -Z; then echo OK;
            else echo sc-tables differ for WOT and EAH; exit 1; fi

            if diff WOT2EAHsc_phonotactics.tsv
            .circleci_backup/WOT2EAHsc_phonotactics.tsv
            --strip-trailing-cr -B -Z; then echo OK;
            else echo sc-tables differ for WOT and EAH; exit 1; fi

      - run:
          name: Evaluate vertical predictions, check if output OK
          command: >
            cd ronataswestoldturkic && cldfbench
            ronataswestoldturkic.evalsc H EAH
            "[10, 100, 500, 700, 1000, 5000, 7000]"

            cd loanpy && if diff tpfpH2EAH.json
            .circleci_backup/tpfpH2EAH.json; then echo OK;
            else echo tpfp differ; exit 1; fi

      - run:
          name: Evaluate horizontal predictions, check if output OK
          command: >
            cd ronataswestoldturkic && cldfbench
            ronataswestoldturkic.evalsc WOT EAH
            "[10, 100, 500, 700, 1000, 5000, 7000]" True True heur.json

            cd loanpy &&
            if diff tpfpWOT2EAH.json .circleci_backup/tpfpWOT2EAH.json;
            then echo OK; else echo tpfp differ; exit 1; fi

      - run:
          name: Plot evaluations, check if jpegs were written
          command: >
            cd ronataswestoldturkic && cldfbench
            ronataswestoldturkic.plot_eval H EAH

            cldfbench ronataswestoldturkic.plot_eval WOT EAH

            cd loanpy && test -e WOT2EAH.jpeg && echo "OK" || exit 1

            test -e H2EAH.jpeg && echo "OK" || exit 1




workflows:
  main:
    jobs:
      - build
