version: 2

build:
  image: latest

python:
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - method: pip
      extra_requirements:
      	- ipatok==0.4.1
      	- epitran==1.24
        - git+https://github.com/martino-vic/loanpy.git@2.0.1

sphinx:
  configuration: docs/conf.py


